{
 "title": "Kyuubi",
 "tags": [ "charm: kyuubi-k8s" ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "baseFilter",
    "label": "baseFilter",
    "query": "job=~\"kyuubi\""
   },
   { "name": "baseLegend", "label": "baseLegend", "query": "{{instance}}" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kyuubi_jvm_uptime, instance)"
    }
   },
   {
    "name": "connType",
    "label": "connType",
    "query": "thrift_binary_connection,rest_connection,thrift_http_connection,metadata_request"
   },
   {
    "name": "opType",
    "label": "opType",
    "query": "ExecuteStatement,BatchJobSubmission,LaunchEngine"
   },
   { "name": "trendInterval", "label": "trendInterval", "query": "1m,5m,15m,30m,1h,3h,6h,12h,24h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyuubi_jvm_uptime{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_jvm_uptime{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "KeyStore Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_thrift_ssl_cert_expiration{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Connection Opened",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kyuubi_connection_opened_INTERACTIVE{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "total-interactive"
    },
    {
     "expr": "sum(kyuubi_connection_opened_BATCH{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "total-batch"
    },
    {
     "expr": "kyuubi_connection_opened_INTERACTIVE{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": "kyuubi_connection_opened_BATCH{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Engine Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "kyuubi_engine_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Exec Pool Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kyuubi_exec_pool_threads_alive{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-alive"
    },
    {
     "expr": "kyuubi_exec_pool_threads_active{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-active"
    },
    {
     "expr": "kyuubi_exec_pool_threads_queue{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-queue"
    }
   ]
  },
  {
   "title": "Engine Launching",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_LaunchEngine_running_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": "kyuubi_operation_state_BatchJobSubmission_pending_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Engine startup permit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kyuubi_engine_startup_permit_limit_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-limit"
    },
    {
     "expr": "kyuubi_engine_startup_permit_waiting{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-waiting"
    },
    {
     "expr": "kyuubi_engine_startup_permit_available{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}-available"
    }
   ]
  },
  {
   "title": "Max Batch Pending Elapse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kyuubi_operation_batch_pending_max_elapse{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Session(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_connection_total_INTERACTIVE{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": "increase(kyuubi_connection_total_BATCH{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Operation(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_operation_total_ExecuteStatement{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-interactive"
    },
    {
     "expr": "increase(kyuubi_operation_total_BatchJobSubmission{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-batch"
    }
   ]
  },
  {
   "title": "Fetch Rows[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_backend_service_fetch_result_rows_rate_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-result"
    },
    {
     "expr": "increase(kyuubi_backend_service_fetch_log_rows_rate_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}-log"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_total_used{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage(Ratio)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_total_used{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} / kyuubi_memory_usage_heap_max{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "JVM GC Count[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(kyuubi_gc_ZGC_Cycles_count{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    },
    {
     "expr": "increase(kyuubi_gc_G1_MarkSweep_count{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  { "title": "Connection($connType)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "connType" },
  {
   "title": "$connType(opened)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_opened{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_${connType}_opened{instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    },
    {
     "expr": "kyuubi_${connType}_total_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$connType(failed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_${connType}_failed{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    },
    {
     "expr": "kyuubi_${connType}_failed_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  { "title": "Operation($opType)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "opType" },
  {
   "title": "Jobs Stat",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_running_total",
     "legendFormat": "running"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_finished_total",
     "legendFormat": "finished"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_error_total",
     "legendFormat": "error"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_pending_total",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "$opType(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kyuubi_operation_total_${opType}{instance=~\"$instance\"}[$trendInterval])",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  {
   "title": "$opType(pending/running)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_pending_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-pending"
    },
    {
     "expr": "kyuubi_operation_state_${opType}_running_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-running"
    }
   ]
  },
  {
   "title": "$opType(closed/finished)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_closed_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-closed"
    },
    {
     "expr": "kyuubi_operation_state_${opType}_finished_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend-finished"
    }
   ]
  },
  {
   "title": "$opType(error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_${opType}_error_total{instance=~\"$instance\"}",
     "legendFormat": "$baseLegend"
    }
   ]
  },
  { "title": "Extra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Metadata Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "kyuubi_metadata_request_opened{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Opened"
    },
    {
     "expr": "kyuubi_metadata_request_total_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Total"
    },
    {
     "expr": "kyuubi_metadata_request_failed_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Failed"
    },
    {
     "expr": "kyuubi_metadata_request_retrying_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Retring"
    }
   ]
  },
  {
   "title": "Metadata Request(new)[$trendInterval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "increase(kyuubi_metadata_request_total_total{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}[$trendInterval])",
     "legendFormat": "${baseLegend}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "kyuubi_thread_state_runnable_count{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Runnable"
    },
    {
     "expr": "kyuubi_thread_state_blocked_count{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Blocked"
    },
    {
     "expr": "kyuubi_thread_state_waiting_count{instance=~\"$instance\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "${baseLegend} Waiting"
    }
   ]
  },
  {
   "title": "JVM Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_G1_Eden_Space_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Eden_Space_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Eden_Space_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Eden Space Max"
      }
     ]
    },
    {
     "title": "Old Gen",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_G1_Old_Gen_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_CMS_Old_Gen_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_CMS_Old_Gen_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Old Gen Max"
      }
     ]
    },
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_G1_Survivor_Space_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Survivor_Space_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Par_Survivor_Space_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Survivor Space Max"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Metaspace_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Metaspace Max"
      }
     ]
    },
    {
     "title": "Compressed Class",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Compressed_Class_Space_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Compressed Class Max"
      }
     ]
    },
    {
     "title": "Code Cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_used{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Used"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_committed{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Committed"
      },
      {
       "expr": "kyuubi_memory_usage_pools_Code_Cache_max{instance=~\"$instance\"}",
       "legendFormat": "${baseLegend} Code Cache Max"
      }
     ]
    }
   ]
  }
 ]
}