# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: GPU Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install tox
        run: pipx install tox
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install tox
        run: pipx install tox
      - name: Run tests
        run: tox run -e unit

  build:
    strategy:
      matrix:
        path:
          - .
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v32.0.0
    with:
      path-to-charm-directory: ${{ matrix.path }}

  start-runner:
    name: Start self-hosted EC2 runner
    needs: [build]
    runs-on: ubuntu-22.04
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: start
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          ec2-image-id: ${{ vars.AWS_EC2_IMAGE_ID }}
          ec2-instance-type: ${{ vars.AWS_EC2_INSTANCE_TYPE }}
          subnet-id: ${{ vars.AWS_DEFAULT_SUBNET_ID }}
          security-group-id: ${{ vars.AWS_SECURITY_GROUP_ID }}

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        tox-environments:
          - integration-charm
    name: ${{ matrix.tox-environments }}
    needs:
      - lint
      - unit-test
      - build
      - start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install required packages/snaps
        run: |
          systemctl disable unattended-upgrades
          systemctl stop unattended-upgrades
          apt purge unattended-upgrades -y
          apt update
          apt install build-essential python3-dev libpq-dev -yqq pipx
          snap install yq
          snap install juju --channel 3.6/stable
          snap install microk8s --channel 1.32/stable --classic
          snap alias microk8s.kubectl kubectl
          usermod -aG microk8s ubuntu

      - name: Setup microceph
        run: |
          sudo snap install microceph
          sudo microceph cluster bootstrap
          sudo microceph disk add loop,1G,3
          sudo microceph enable rgw
          sudo microceph.radosgw-admin user create --uid test --display-name test --access-key=foo --secret-key=bar

      - name: Configure user, microk8s and juju
        run: |
          su ubuntu -c "/bin/bash ./tests/integration/setup/setup-ec2-gpu.sh"
        timeout-minutes: 20

      - name: Download packed charm(s)
        uses: actions/download-artifact@v5
        with:
          artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
          merge-multiple: true
          path: /home/ubuntu/workdir

      - name: Run integration tests
        run: |
          mv ./** /home/ubuntu/workdir
          chown -R ubuntu /home/ubuntu
          cd /home/ubuntu/workdir
          echo -e "ENDPOINT=http://$(ip -4 -j route get 2.2.2.2 | yq '.[].prefsrc'):80/\nACCESS_KEY=foo\nSECRET_KEY=bar" > .env
          chown ubuntu:ubuntu .env
          cat .env
          su ubuntu -c "~/.local/bin/tox run -e integration-gpu"

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - integration-test
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: stop
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
