# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install tox
        run: pipx install tox
      - name: Run linters
        run: tox run -e lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install tox
        run: pipx install tox
      - name: Run tests
        run: tox run -e unit

  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@e5539256480675584841600b2f6291c38bc6d4f7 # v50.2.1

  integration-test:
    name: Integration tests
    needs:
      - lint
      - unit-tests
      - build
    uses: ./.github/workflows/integration-test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      mark-expression: ${{ github.event_name != 'schedule' && 'not unstable' || '' }}
    secrets: inherit

  integration-gpu-amd:
    name: GPU tests (amd64)
    needs:
      - lint
      - unit-tests
      - build
    uses: ./.github/workflows/integration-gpu.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      arch: amd64
    secrets: inherit

  integration-gpu-arm:
    name: GPU tests (arm64)
    # TODO(zk-arm): Missing arm64 support for ZK
    # TODO(GH#165): Convert to Canonical K8s
    if: false
    needs:
      - lint
      - unit-tests
      - build
    uses: ./.github/workflows/integration-gpu.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      arch: arm64
    secrets: inherit

  refresh-tests:
    name: Inplace upgrades
    needs:
      - lint
      - unit-tests
      - build
    uses: ./.github/workflows/refresh-tests.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets: inherit
