# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: GPU Tests

on:
  workflow_call:
    inputs:
      arch:
        type: string
        default: "amd64"
        required: true

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-22.04
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: start
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          ec2-image-id: ${{ inputs.arch == 'amd64' && vars.AWS_EC2_IMAGE_ID_AMD || vars.AWS_EC2_IMAGE_ID_ARM }}
          ec2-instance-type: ${{ inputs.arch == 'amd64' && vars.AWS_EC2_INSTANCE_TYPE_AMD || vars.AWS_EC2_INSTANCE_TYPE_ARM }}
          subnet-id: ${{ vars.AWS_DEFAULT_SUBNET_ID }}
          security-group-id: ${{ vars.AWS_SECURITY_GROUP_ID }}

  integration-tests:
    name: Run integration tests
    needs: [start-runner]
    runs-on: ${{ needs.start-runner.outputs.label }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup environment
        run: |
          sudo systemctl disable --now unattended-upgrades.service
          sudo apt autoremove unattended-upgrades -y
          sudo apt update
          sudo apt install build-essential -yqq

          sudo snap install concierge --classic
          sudo concierge prepare -c tests/integration/setup/concierge_gpu.yaml

          mkdir -p /home/ubuntu/.kube
          sudo chown -f -R ubuntu /home/ubuntu/.kube
          sudo microk8s config | tee /home/ubuntu/.kube/config
          sudo chown ubuntu /home/ubuntu/.kube/config

      - name: Setup object storage
        run: |
          sudo microceph cluster bootstrap
          sudo microceph disk add loop,1G,3
          sudo microceph enable rgw
          sudo microceph.radosgw-admin user create --uid test --display-name test --access-key=foo --secret-key=bar
          aws configure set aws_access_key_id foo
          aws configure set aws_secret_access_key bar
          aws configure set endpoint_url "http://$(ip -4 -j route get 2.2.2.2 | yq -r '.[] | .prefsrc'):80"
          aws s3 ls

      - name: Bootstrap juju model
        run: |
          su ubuntu -c "/bin/bash ./tests/integration/setup/setup-ec2-gpu.sh"
        timeout-minutes: 20

      - name: Download packed charm(s)
        uses: actions/download-artifact@v7
        with:
          artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
          merge-multiple: true
          path: /home/ubuntu/workdir

      - name: Run integration tests
        run: |
          mv ./** /home/ubuntu/workdir
          chown -R ubuntu /home/ubuntu
          cd /home/ubuntu/workdir
          echo -e "S3_SERVER_URL=http://$(ip -4 -j route get 2.2.2.2 | yq '.[].prefsrc'):80/\nS3_ACCESS_KEY=foo\nS3_SECRET_KEY=bar" > .env
          chown ubuntu:ubuntu .env
          su ubuntu -c "~/.local/bin/tox run -e integration-gpu"

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner
      - integration-tests
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2.4.1
        with:
          mode: stop
          github-token: ${{ secrets.WELPAOLO_GITHUB_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
